import { Topic } from '../../../types';
import { TYPESCRIPT_ADVANCED_TYPES_BEGINNER_TOPICS } from './beginner';
import { TYPESCRIPT_ADVANCED_TYPES_INTERMEDIATE_TOPICS } from './intermediate';
import { TYPESCRIPT_ADVANCED_TYPES_ADVANCED_TOPICS } from './advanced';

export const TYPESCRIPT_ADVANCED_TYPES_TOPICS: Topic[] = [
  ...TYPESCRIPT_ADVANCED_TYPES_BEGINNER_TOPICS,
  ...TYPESCRIPT_ADVANCED_TYPES_INTERMEDIATE_TOPICS,
  ...TYPESCRIPT_ADVANCED_TYPES_ADVANCED_TOPICS
];
