import { Topic } from '../../../types';
import { TYPESCRIPT_FUNCTIONS_BEGINNER_TOPICS } from './beginner';
import { TYPESCRIPT_FUNCTIONS_INTERMEDIATE_TOPICS } from './intermediate';
import { TYPESCRIPT_FUNCTIONS_ADVANCED_TOPICS } from './advanced';

export const TYPESCRIPT_FUNCTIONS_TOPICS: Topic[] = [
  ...TYPESCRIPT_FUNCTIONS_BEGINNER_TOPICS,
  ...TYPESCRIPT_FUNCTIONS_INTERMEDIATE_TOPICS,
  ...TYPESCRIPT_FUNCTIONS_ADVANCED_TOPICS
];
