import { Topic } from '../../../types';
import { TYPESCRIPT_REACT_TYPING_INTERMEDIATE_TOPICS } from './intermediate';
import { TYPESCRIPT_REACT_TYPING_ADVANCED_TOPICS } from './advanced';

export const TYPESCRIPT_REACT_TYPING_TOPICS: Topic[] = [
  ...TYPESCRIPT_REACT_TYPING_INTERMEDIATE_TOPICS,
  ...TYPESCRIPT_REACT_TYPING_ADVANCED_TOPICS
];
