import { Topic } from '../../../types';
import { TYPESCRIPT_ANGULAR_TYPING_INTERMEDIATE_TOPICS } from './intermediate';
import { TYPESCRIPT_ANGULAR_TYPING_ADVANCED_TOPICS } from './advanced';

export const TYPESCRIPT_ANGULAR_TYPING_TOPICS: Topic[] = [
  ...TYPESCRIPT_ANGULAR_TYPING_INTERMEDIATE_TOPICS,
  ...TYPESCRIPT_ANGULAR_TYPING_ADVANCED_TOPICS
];
