import { Topic } from '../../../types';
import { SECURITY_API_SECURITY_BEGINNER_TOPICS } from './beginner';
import { SECURITY_API_SECURITY_INTERMEDIATE_TOPICS } from './intermediate';
import { SECURITY_API_SECURITY_ADVANCED_TOPICS } from './advanced';

export const SECURITY_API_SECURITY_TOPICS: Topic[] = [
  ...SECURITY_API_SECURITY_BEGINNER_TOPICS,
  ...SECURITY_API_SECURITY_INTERMEDIATE_TOPICS,
  ...SECURITY_API_SECURITY_ADVANCED_TOPICS
];
