import { Topic } from '../../../types';
import { TYPESCRIPT_CONFIG_TOOLS_BEGINNER_TOPICS } from './beginner';
import { TYPESCRIPT_CONFIG_TOOLS_INTERMEDIATE_TOPICS } from './intermediate';
import { TYPESCRIPT_CONFIG_TOOLS_ADVANCED_TOPICS } from './advanced';

export const TYPESCRIPT_CONFIG_TOOLS_TOPICS: Topic[] = [
  ...TYPESCRIPT_CONFIG_TOOLS_BEGINNER_TOPICS,
  ...TYPESCRIPT_CONFIG_TOOLS_INTERMEDIATE_TOPICS,
  ...TYPESCRIPT_CONFIG_TOOLS_ADVANCED_TOPICS
];
