import { Topic } from '../../../types';
import { SECURITY_AUTHENTICATION_BEGINNER_TOPICS } from './beginner';
import { SECURITY_AUTHENTICATION_INTERMEDIATE_TOPICS } from './intermediate';
import { SECURITY_AUTHENTICATION_ADVANCED_TOPICS } from './advanced';

export const SECURITY_AUTHENTICATION_TOPICS: Topic[] = [
  ...SECURITY_AUTHENTICATION_BEGINNER_TOPICS,
  ...SECURITY_AUTHENTICATION_INTERMEDIATE_TOPICS,
  ...SECURITY_AUTHENTICATION_ADVANCED_TOPICS
];
