import { Topic } from '../../../types';
import { TYPESCRIPT_INTERFACES_TYPES_BEGINNER_TOPICS } from './beginner';
import { TYPESCRIPT_INTERFACES_TYPES_INTERMEDIATE_TOPICS } from './intermediate';
import { TYPESCRIPT_INTERFACES_TYPES_ADVANCED_TOPICS } from './advanced';

export const TYPESCRIPT_INTERFACES_TYPES_TOPICS: Topic[] = [
  ...TYPESCRIPT_INTERFACES_TYPES_BEGINNER_TOPICS,
  ...TYPESCRIPT_INTERFACES_TYPES_INTERMEDIATE_TOPICS,
  ...TYPESCRIPT_INTERFACES_TYPES_ADVANCED_TOPICS
];
