import { Topic } from '../../../types';
import { SECURITY_DATA_STORAGE_BEGINNER_TOPICS } from './beginner';
import { SECURITY_DATA_STORAGE_INTERMEDIATE_TOPICS } from './intermediate';
import { SECURITY_DATA_STORAGE_ADVANCED_TOPICS } from './advanced';

export const SECURITY_DATA_STORAGE_TOPICS: Topic[] = [
  ...SECURITY_DATA_STORAGE_BEGINNER_TOPICS,
  ...SECURITY_DATA_STORAGE_INTERMEDIATE_TOPICS,
  ...SECURITY_DATA_STORAGE_ADVANCED_TOPICS
];
