import { Topic } from '../../../types';
import { TYPESCRIPT_ERRORS_DEBUGGING_BEGINNER_TOPICS } from './beginner';
import { TYPESCRIPT_ERRORS_DEBUGGING_INTERMEDIATE_TOPICS } from './intermediate';
import { TYPESCRIPT_ERRORS_DEBUGGING_ADVANCED_TOPICS } from './advanced';

export const TYPESCRIPT_ERRORS_DEBUGGING_TOPICS: Topic[] = [
  ...TYPESCRIPT_ERRORS_DEBUGGING_BEGINNER_TOPICS,
  ...TYPESCRIPT_ERRORS_DEBUGGING_INTERMEDIATE_TOPICS,
  ...TYPESCRIPT_ERRORS_DEBUGGING_ADVANCED_TOPICS
];
