import { Topic } from '../../../types';
import { TYPESCRIPT_GENERICS_BEGINNER_TOPICS } from './beginner';
import { TYPESCRIPT_GENERICS_INTERMEDIATE_TOPICS } from './intermediate';
import { TYPESCRIPT_GENERICS_ADVANCED_TOPICS } from './advanced';

export const TYPESCRIPT_GENERICS_TOPICS: Topic[] = [
  ...TYPESCRIPT_GENERICS_BEGINNER_TOPICS,
  ...TYPESCRIPT_GENERICS_INTERMEDIATE_TOPICS,
  ...TYPESCRIPT_GENERICS_ADVANCED_TOPICS
];
